module.exports = function () {
    return { 
        categories: [{name: "Watersports", code: "WS"}, {name: "Soccer", code: "SC"}, {name: "Chess", code: "CH"}],
        products: [
            { id: 1, name: "Kayak", category: "Watersports", 
                description: "A boat for one person", price: 275, releaseDate:  new Date().toISOString()},    // UTC dátumok
            { id: 2, name: "Lifejacket", category: "Watersports", 
                description: "Protective and fashionable", price: 48.95,  releaseDate:  new Date().toISOString()},
            { id: 3, name: "Soccer Ball", category: "Soccer", 
                description: "FIFA-approved size and weight", price: 19.50,  releaseDate:  new Date().toISOString() },
            { id: 4, name: "Corner Flags", category: "Soccer", 
                description: "Give your playing field a professional touch", 
                price: 34.95, releaseDate:  new Date().toISOString()},
            { id: 5, name: "Stadium", category: "Soccer", 
                description: "Flat-packed 35,000-seat stadium", price: 79500 , releaseDate:  new Date().toISOString()},
            { id: 6, name: "Thinking Cap", category: "Chess", 
                description: "Improve brain efficiency by 75%", price: 16, releaseDate:  new Date().toISOString()},
            { id: 7, name: "Unsteady Chair", category: "Chess", 
                description: "Secretly give your opponent a disadvantage", 
                price: 29.95, releaseDate:  new Date().toISOString()},
            { id: 8, name: "Human Chess Board", category: "Chess", 
                description: "A fun game for the family", price: 75, releaseDate:  new Date().toISOString()},
            { id: 9, name: "Bling Bling King", category: "Chess", 
                description: "Gold-plated, diamond-studded King", price: 1200, releaseDate:  new Date().toISOString()},
        ],
        orders: [],
        books: [
            {   id: '34324233', 
                isbn: '34324233', 
                sellers: [
                    {name: 'Bende seller', address: 'sáky u 7a', quantity: 33000, age: 49, birthYear: 1972},
                    {name: 'Sasform Agrotechnika Kft.', address: 'Felsőszéktó 86', quantity: 12000, age: 40, birthYear: 1981}
                    ],
                title: "Angular 11", 
                authors: ['Ferdinand Malcher', 'Johannes Hoppe', 'Danny Koppenhagen'], 
                published:  new Date().toISOString(), subtitle: 'Grundlagen, fortgeschrittene Themen und Best Practices', rating: 5,
                thumbnails: [{
                    url: 'https://ng-buch.de/angular-cover.jpg', title: 'Buchcover' }],
                description: 'Lernen Sie Angular mit diesem Praxisbuch!',
                genres: ['IT', 'Programming'],
                ebook: false,
                printed: false,
                availability: 'Available',
                level: 'Beginner'
            },
            {   id: '554543654', 
                isbn: '554543654', 
                title: "React", 
                authors: ['Oliver Zeigermann', 'Nils Hartmann'], 
                subtitle: 'Grundlagen, fortgeschrittene Themen, Praxistipps', rating: 4,
                thumbnails: [{
                    url: 'https://ng-buch.de/react-cover.jpg', title: 'Buchcover' }],
                description: 'Das bewährte und umfassende Praxisbuch zu React',
                genres: ['IT', 'Programming', 'Docker'],
                ebook: true,
                printed: false,
                availability: 'Available',
                level: 'Intermediate'
            },
            {   id: '1111', 
                isbn: '1111', 
                title: "React 1", 
                authors: ['Oliver Zeigermann', 'Nils Hartmann'], 
                subtitle: 'Grundlagen, fortgeschrittene Themen, Praxistipps', rating: 4,
                description: 'Das bewährte und umfassende Praxisbuch zu React',
                genres: ['IT', 'Programming', 'Docker'],
                ebook: true,
                printed: false,
                availability: 'Available',
                level: 'Advanced'
            },
            {   id: '2222', 
                isbn: '2222', 
                title: "React 2", 
                authors: ['Oliver Zeigermann', 'Nils Hartmann'], 
                subtitle: 'Grundlagen, fortgeschrittene Themen, Praxistipps', rating: 4,
                thumbnails: [{
                    url: 'https://ng-buch.de/react-cover.jpg', title: 'Buchcover' }],
                description: 'Das bewährte und umfassende Praxisbuch zu React',
                genres: ['IT', 'Programming', 'Docker'],
                ebook: true,
                printed: false,
                availability: 'Available'
            },
            {   id: '3333', 
                isbn: '3333', 
                title: "React 3", 
                authors: ['Oliver Zeigermann', 'Nils Hartmann'], 
                subtitle: 'Grundlagen, fortgeschrittene Themen, Praxistipps', rating: 4,
                thumbnails: [{
                    url: 'https://ng-buch.de/react-cover.jpg', title: 'Buchcover' }],
                description: 'Das bewährte und umfassende Praxisbuch zu React',
                genres: ['IT', 'Programming', 'Docker'],
                ebook: true,
                printed: false,
                availability: 'Available',
                level: 'Beginner'
            },
            {   id: '4444', 
                isbn: '4444', 
                title: "React 4", 
                authors: ['Oliver Zeigermann', 'Nils Hartmann'], 
                subtitle: 'Grundlagen, fortgeschrittene Themen, Praxistipps', rating: 4,
                description: 'Das bewährte und umfassende Praxisbuch zu React',
                genres: ['IT', 'Programming', 'Docker'],
                ebook: true,
                printed: false,
                availability: 'Available',
                level: 'Advanced'
            },
            {   id: '5555', 
                isbn: '5555', 
                title: "React 5", 
                authors: ['Oliver Zeigermann', 'Nils Hartmann'], 
                subtitle: 'Grundlagen, fortgeschrittene Themen, Praxistipps', rating: 4,
                description: 'Das bewährte und umfassende Praxisbuch zu React',
                genres: ['IT', 'Programming', 'Docker'],
                ebook: true,
                printed: false,
                availability: 'Available'
            },
            {   id: '6666', 
                isbn: '6666', 
                title: "React 6", 
                authors: ['Oliver Zeigermann', 'Nils Hartmann'], 
                subtitle: 'Grundlagen, fortgeschrittene Themen, Praxistipps', rating: 4,
                description: 'Das bewährte und umfassende Praxisbuch zu React',
                genres: ['IT', 'Programming', 'Docker'],
                ebook: true,
                printed: false,
                availability: 'Available'
            },
            {   id: '7777', 
                isbn: '7777', 
                title: "React 7", 
                authors: ['Oliver Zeigermann', 'Nils Hartmann'], 
                subtitle: 'Grundlagen, fortgeschrittene Themen, Praxistipps', rating: 4,
                description: 'Das bewährte und umfassende Praxisbuch zu React',
                genres: ['IT', 'Programming', 'Docker'],
                ebook: true,
                printed: false,
                availability: 'Available'
            },
            {   id: '8888', 
                isbn: '8888', 
                title: "React 8", 
                authors: ['Oliver Zeigermann', 'Nils Hartmann'], 
                subtitle: 'Grundlagen, fortgeschrittene Themen, Praxistipps', rating: 4,
                description: 'Das bewährte und umfassende Praxisbuch zu React',
                genres: ['IT', 'Programming', 'Docker'],
                ebook: true,
                printed: false,
                availability: 'Available'
            },
            {   id: '9999', 
                isbn: '9999', 
                title: "React 9", 
                authors: ['Oliver Zeigermann', 'Nils Hartmann'], 
                subtitle: 'Grundlagen, fortgeschrittene Themen, Praxistipps', rating: 4,
                description: 'Das bewährte und umfassende Praxisbuch zu React',
                genres: ['IT', 'Programming', 'Docker'],
                ebook: true,
                printed: false,
                availability: 'Available'
            }
        ],
        menetvonalak: [
            {
                menetvonalId: 001,
                vonatszam: 82051,
                kozlNapja: new Date().toISOString(),
                indAlloms: "Dunaföldvár",
                erkAllomas: "Előszállási i. ipvk",
                vonatNev: "exPET / exPEDE",
            },
            {
                menetvonalId: 002,
                vonatszam: 82051,
                kozlNapja: new Date().toISOString(),
                indAlloms: "Dunaföldvár",
                erkAllomas: "Előszállási i. ipvk",
                vonatNev: "exPET / exPEDE",
            },
            {
                menetvonalId: 003,
                vonatszam: 82051,
                kozlNapja: new Date().toISOString(),
                indAlloms: "Dunaföldvár",
                erkAllomas: "Előszállási i. ipvk",
                vonatNev: "exPET / exPEDE",
            },{
                menetvonalId: 004,
                vonatszam: 82052,
                kozlNapja: new Date().toISOString(),
                indAlloms: "Kecskemét",
                erkAllomas: "Előszállási i. ipvk",
                vonatNev: "exPET / exPEDE",
            },{
                menetvonalId: 005,
                vonatszam: 82052,
                kozlNapja: new Date().toISOString(),
                indAlloms: "Szolnok",
                erkAllomas: "Előszállási i. ipvk",
                vonatNev: "exPET / exPEDE",
            },
            {
                menetvonalId: 006,
                vonatszam: 82051,
                kozlNapja: new Date().toISOString(),
                indAlloms: "Dunaföldvár",
                erkAllomas: "Előszállási i. ipvk",
                vonatNev: "exPET / exPEDE",
            },
            {
                menetvonalId: 007,
                vonatszam: 82051,
                kozlNapja: new Date().toISOString(),
                indAlloms: "Dunaföldvár",
                erkAllomas: "Előszállási i. ipvk",
                vonatNev: "exPET / exPEDE",
            },
            {
                menetvonalId: 008,
                vonatszam: 82051,
                kozlNapja: new Date().toISOString(),
                indAlloms: "Dunaföldvár",
                erkAllomas: "Előszállási i. ipvk",
                vonatNev: "exPET / exPEDE",
            },{
                menetvonalId: 009,
                vonatszam: 82052,
                kozlNapja: new Date().toISOString(),
                indAlloms: "Kecskemét",
                erkAllomas: "Előszállási i. ipvk",
                vonatNev: "exPET / exPEDE",
            },{
                menetvonalId: 010,
                vonatszam: 82052,
                kozlNapja: new Date().toISOString(),
                indAlloms: "Szolnok",
                erkAllomas: "Előszállási i. ipvk",
                vonatNev: "exPET / exPEDE",
            },
            {
                menetvonalId: 011,
                vonatszam: 82051,
                kozlNapja: new Date().toISOString(),
                indAlloms: "Dunaföldvár",
                erkAllomas: "Előszállási i. ipvk",
                vonatNev: "exPET / exPEDE",
            },
            {
                menetvonalId: 012,
                vonatszam: 82051,
                kozlNapja: new Date().toISOString(),
                indAlloms: "Dunaföldvár",
                erkAllomas: "Előszállási i. ipvk",
                vonatNev: "exPET / exPEDE",
            },
            {
                menetvonalId: 013,
                vonatszam: 82051,
                kozlNapja: new Date().toISOString(),
                indAlloms: "Dunaföldvár",
                erkAllomas: "Előszállási i. ipvk",
                vonatNev: "exPET / exPEDE",
            },{
                menetvonalId: 014,
                vonatszam: 82052,
                kozlNapja: new Date().toISOString(),
                indAlloms: "Kecskemét",
                erkAllomas: "Előszállási i. ipvk",
                vonatNev: "exPET / exPEDE",
            },{
                menetvonalId: 015,
                vonatszam: 82052,
                kozlNapja: new Date().toISOString(),
                indAlloms: "Szolnok",
                erkAllomas: "Előszállási i. ipvk",
                vonatNev: "exPET / exPEDE",
            }
        ],
        megrendelesek: [
            {
                id: 001,
                azonosito: "2021/198/0",
                mettol: new Date().toISOString(),
                meddig: new Date().toISOString(),
                megjegyzes: ""
            }
        ],
        menetrendek: [
            {
                id: 001,
                allomas: "Dunaföldvár",
                esemeny: "indulas",
                tavolsag: 5.00,
                indIdo: new Date(2020, 11, 12, 13, 23, 00).toISOString(),
                erkIdo: new Date(2020, 11, 13, 17, 23, 00).toISOString(),
            }
        ],
        vonatok: [
            {
                risAzonosito: 'RHU20Fow',
                tetel: 1,
                tovabbMod: 'onallo',
                kozlekMod: 'rakott',
                feladasiAllomas: 'Brainevo',
                indulasiAllomas: 'Szob oh.',
                erkezesiAllomas: 'Tiszapakonya',
                rendeltetesiAllomas: 'Miskolc',
                elertAllomas: 'Most Novie',
                atado: 'Lajos',
                atvevo: 'Miklós',
                tervIdo: new Date(2020, 11, 12, 13, 23, 00).toISOString(),
                erkIdo: new Date(2020, 11, 13, 17, 23, 00).toISOString(),
                kocsiDb: 23,
                kocsiL: false,
                RID: true,
                RK: false
            },
            {
                risAzonosito: 'RHU21Fow',
                tetel: 1,
                tovabbMod: 'onallo',
                kozlekMod: 'rakott',
                feladasiAllomas: 'Brainevo',
                indulasiAllomas: 'Szob oh.',
                erkezesiAllomas: 'Tiszapakonya',
                rendeltetesiAllomas: 'Miskolc',
                elertAllomas: 'Most Novie',
                atado: 'Laja',
                atvevo: 'Miklós',
                tervIdo: new Date(2020, 11, 12, 13, 23, 00).toISOString(),
                erkIdo: new Date(2020, 11, 13, 17, 23, 00).toISOString(),
                kocsiDb: 23,
                kocsiL: false,
                RID: true,
                RK: false
            },  {
                risAzonosito: 'RHU22Fow',
                tetel: 1,
                tovabbMod: 'onallo',
                kozlekMod: 'rakott',
                feladasiAllomas: 'Brainevo',
                indulasiAllomas: 'Szob oh.',
                erkezesiAllomas: 'Tiszapakonya',
                rendeltetesiAllomas: 'Miskolc',
                elertAllomas: 'Most Novie',
                atado: 'Pista',
                atvevo: 'Miklós',
                tervIdo: new Date(2020, 11, 12, 13, 23, 00).toISOString(),
                erkIdo: new Date(2020, 11, 13, 17, 23, 00).toISOString(),
                kocsiDb: 23,
                kocsiL: false,
                RID: true,
                RK: false
            },  {
                risAzonosito: 'RHU23Fow',
                tetel: 1,
                tovabbMod: 'onallo',
                kozlekMod: 'rakott',
                feladasiAllomas: 'Brainevo',
                indulasiAllomas: 'Szob oh.',
                erkezesiAllomas: 'Tiszapakonya',
                rendeltetesiAllomas: 'Miskolc',
                elertAllomas: 'Most Novie',
                atado: 'Karcsi',
                atvevo: 'Miklós',
                tervIdo: new Date(2020, 11, 12, 13, 23, 00).toISOString(),
                erkIdo: new Date(2020, 11, 13, 17, 23, 00).toISOString(),
                kocsiDb: 23,
                kocsiL: false,
                RID: true,
                RK: false
            },  {
                risAzonosito: 'RHU24Fow',
                tetel: 1,
                tovabbMod: 'onallo',
                kozlekMod: 'rakott',
                feladasiAllomas: 'Brainevo',
                indulasiAllomas: 'Szob oh.',
                erkezesiAllomas: 'Tiszapakonya',
                rendeltetesiAllomas: 'Miskolc',
                elertAllomas: 'Most Novie',
                atado: 'feri',
                atvevo: 'Miklós',
                tervIdo: new Date(2020, 11, 12, 13, 23, 00).toISOString(),
                erkIdo: new Date(2020, 11, 13, 17, 23, 00).toISOString(),
                kocsiDb: 23,
                kocsiL: false,
                RID: true,
                RK: false
            },
            {
                risAzonosito: 'RHU25Fow',
                tetel: 1,
                tovabbMod: 'onallo',
                kozlekMod: 'rakott',
                feladasiAllomas: 'Brainevo',
                indulasiAllomas: 'Szob oh.',
                erkezesiAllomas: 'Tiszapakonya',
                rendeltetesiAllomas: 'Miskolc',
                elertAllomas: 'Most Novie',
                atado: 'feri',
                atvevo: 'Miklós',
                tervIdo: new Date(2020, 11, 12, 13, 23, 00).toISOString(),
                erkIdo: new Date(2020, 11, 13, 17, 23, 00).toISOString(),
                kocsiDb: 23,
                kocsiL: false,
                RID: true,
                RK: false
            },
            {
                risAzonosito: 'RHU26Fow',
                tetel: 1,
                tovabbMod: 'onallo',
                kozlekMod: 'rakott',
                feladasiAllomas: 'Brainevo',
                indulasiAllomas: 'Szob oh.',
                erkezesiAllomas: 'Tiszapakonya',
                rendeltetesiAllomas: 'Miskolc',
                elertAllomas: 'Most Novie',
                atado: 'feri',
                atvevo: 'Miklós',
                tervIdo: new Date(2020, 11, 12, 13, 23, 00).toISOString(),
                erkIdo: new Date(2020, 11, 13, 17, 23, 00).toISOString(),
                kocsiDb: 23,
                kocsiL: false,
                RID: true,
                RK: false
            },
            {
                risAzonosito: 'RHU27Fow',
                tetel: 1,
                tovabbMod: 'onallo',
                kozlekMod: 'rakott',
                feladasiAllomas: 'Brainevo',
                indulasiAllomas: 'Szob oh.',
                erkezesiAllomas: 'Tiszapakonya',
                rendeltetesiAllomas: 'Miskolc',
                elertAllomas: 'Most Novie',
                atado: 'Lajos',
                atvevo: 'Miklós',
                tervIdo: new Date(2020, 11, 12, 13, 23, 00).toISOString(),
                erkIdo: new Date(2020, 11, 13, 17, 23, 00).toISOString(),
                kocsiDb: 23,
                kocsiL: false,
                RID: true,
                RK: false
            },
            {
                risAzonosito: 'RHU28Fow',
                tetel: 1,
                tovabbMod: 'onallo',
                kozlekMod: 'rakott',
                feladasiAllomas: 'Brainevo',
                indulasiAllomas: 'Szob oh.',
                erkezesiAllomas: 'Tiszapakonya',
                rendeltetesiAllomas: 'Miskolc',
                elertAllomas: 'Most Novie',
                atado: 'Lajos',
                atvevo: 'Miklós',
                tervIdo: new Date(2020, 11, 12, 13, 23, 00).toISOString(),
                erkIdo: new Date(2020, 11, 13, 17, 23, 00).toISOString(),
                kocsiDb: 23,
                kocsiL: false,
                RID: true,
                RK: false
            },
            {
                risAzonosito: 'RHU29Fow',
                tetel: 1,
                tovabbMod: 'onallo',
                kozlekMod: 'rakott',
                feladasiAllomas: 'Brainevo',
                indulasiAllomas: 'Szob oh.',
                erkezesiAllomas: 'Tiszapakonya',
                rendeltetesiAllomas: 'Miskolc',
                elertAllomas: 'Most Novie',
                atado: 'Lajos',
                atvevo: 'Miklós',
                tervIdo: new Date(2020, 11, 12, 13, 23, 00).toISOString(),
                erkIdo: new Date(2020, 11, 13, 17, 23, 00).toISOString(),
                kocsiDb: 23,
                kocsiL: false,
                RID: true,
                RK: false
            },
            {
                risAzonosito: 'RHU30Fow',
                tetel: 1,
                tovabbMod: 'onallo',
                kozlekMod: 'rakott',
                feladasiAllomas: 'Brainevo',
                indulasiAllomas: 'Szob oh.',
                erkezesiAllomas: 'Tiszapakonya',
                rendeltetesiAllomas: 'Miskolc',
                elertAllomas: 'Most Novie',
                atado: 'Lajos',
                atvevo: 'Miklós',
                tervIdo: new Date(2020, 11, 12, 13, 23, 00).toISOString(),
                erkIdo: new Date(2020, 11, 13, 17, 23, 00).toISOString(),
                kocsiDb: 23,
                kocsiL: false,
                RID: true,
                RK: false
            },
            {
                risAzonosito: 'RHU31Fow',
                tetel: 1,
                tovabbMod: 'onallo',
                kozlekMod: 'rakott',
                feladasiAllomas: 'Brainevo',
                indulasiAllomas: 'Szob oh.',
                erkezesiAllomas: 'Tiszapakonya',
                rendeltetesiAllomas: 'Miskolc',
                elertAllomas: 'Most Novie',
                atado: 'Lajos',
                atvevo: 'Miklós',
                tervIdo: new Date(2020, 11, 12, 13, 23, 00).toISOString(),
                erkIdo: new Date(2020, 11, 13, 17, 23, 00).toISOString(),
                kocsiDb: 23,
                kocsiL: false,
                RID: true,
                RK: false
            }, {
                risAzonosito: 'RHU32Fow',
                tetel: 1,
                tovabbMod: 'onallo',
                kozlekMod: 'rakott',
                feladasiAllomas: 'Brainevo',
                indulasiAllomas: 'Szob oh.',
                erkezesiAllomas: 'Tiszapakonya',
                rendeltetesiAllomas: 'Miskolc',
                elertAllomas: 'Most Novie',
                atado: 'Lajos',
                atvevo: 'Miklós',
                tervIdo: new Date(2020, 11, 12, 13, 23, 00).toISOString(),
                erkIdo: new Date(2020, 11, 13, 17, 23, 00).toISOString(),
                kocsiDb: 23,
                kocsiL: false,
                RID: true,
                RK: false
            }, {
                risAzonosito: 'RHU33Fow',
                tetel: 1,
                tovabbMod: 'onallo',
                kozlekMod: 'rakott',
                feladasiAllomas: 'Brainevo',
                indulasiAllomas: 'Szob oh.',
                erkezesiAllomas: 'Tiszapakonya',
                rendeltetesiAllomas: 'Miskolc',
                elertAllomas: 'Most Novie',
                atado: 'Lajos',
                atvevo: 'Miklós',
                tervIdo: new Date(2020, 11, 12, 13, 23, 00).toISOString(),
                erkIdo: new Date(2020, 11, 13, 17, 23, 00).toISOString(),
                kocsiDb: 23,
                kocsiL: false,
                RID: true,
                RK: false
            }, {
                risAzonosito: 'RHU34Fow',
                tetel: 1,
                tovabbMod: 'onallo',
                kozlekMod: 'rakott',
                feladasiAllomas: 'Brainevo',
                indulasiAllomas: 'Szob oh.',
                erkezesiAllomas: 'Tiszapakonya',
                rendeltetesiAllomas: 'Miskolc',
                elertAllomas: 'Most Novie',
                atado: 'Lajos',
                atvevo: 'Miklós',
                tervIdo: new Date(2020, 11, 12, 13, 23, 00).toISOString(),
                erkIdo: new Date(2020, 11, 13, 17, 23, 00).toISOString(),
                kocsiDb: 23,
                kocsiL: false,
                RID: true,
                RK: false
            }, {
                risAzonosito: 'RHU35Fow',
                tetel: 1,
                tovabbMod: 'onallo',
                kozlekMod: 'rakott',
                feladasiAllomas: 'Brainevo',
                indulasiAllomas: 'Szob oh.',
                erkezesiAllomas: 'Tiszapakonya',
                rendeltetesiAllomas: 'Miskolc',
                elertAllomas: 'Most Novie',
                atado: 'Lajos',
                atvevo: 'Miklós',
                tervIdo: new Date(2020, 11, 12, 13, 23, 00).toISOString(),
                erkIdo: new Date(2020, 11, 13, 17, 23, 00).toISOString(),
                kocsiDb: 23,
                kocsiL: false,
                RID: true,
                RK: false
            }

        ]
    }
}

/*
    DÁTUM _!!!!
        A RESTből visszajövő json a dátumokat rendszerint nem localizálva hanem az ISO8809 nek megfelelő formátumban adja vissza,
    mely UTC. (a DBben is elvileg UTC kell tárolni). 
        A js new Date() (és valamennyi nem xxxUTCyyy() metódus olyan date objektumot hoz létre, mely a browser local és timezonenak felel meg. )
    A local date-t itt átalakitjuk UTC ISO fomrában a toISOString() gel, igy emuláljuk hogy a API-tól jönnek a dátumok.

    HA viszont nem browserben futo js ben hozzuk létre a Date() akkor UTC időt hoz létre !!!
*/